# Generated by Django 4.2.17 on 2025-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
    ]
