# Generated by Django 4.2.17 on 2024-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apellidos', models.TextField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('departamento', models.TextField(blank=True, max_length=50, null=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
