# Generated by Django 4.2.17 on 2025-02-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('pais', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Desierto', 'Desierto'), ('Montaña', 'Montaña'), ('Playa', 'Playa'), ('Bosque', 'Bosque'), ('Ciudad', 'Ciudad')], max_length=100)),
            ],
            options={
                'db_table': 'lugares',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='lugares')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.lugar')),
            ],
        ),
    ]
