# Generated by Django 4.2.17 on 2025-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugares'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
