# Generated by Django 4.2.17 on 2025-01-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coche',
            table='coche',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
    ]
