# Generated by Django 4.2.17 on 2025-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'estudiantes',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tematica', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('BD', 'Bases de Datos'), ('JS', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Otros', 'Otros')], max_length=100)),
                ('estudiantes', models.ManyToManyField(to='cursos.estudiante')),
            ],
            options={
                'db_table': 'cursos',
                'ordering': ['nombre'],
            },
        ),
    ]
