# Generated by Django 4.2.17 on 2025-01-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
    ]
