# Generated by Django 4.2.17 on 2025-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='activo',
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(default='Presencial', max_length=50),
            preserve_default=False,
        ),
    ]
